# $HOME/.config/alacritty/alacritty.toml
# by Rito Ghosh 2023-10-06

# Alacritty now uses TOML formatting for its config files.
# This is a simple example.

# There are the specification here: https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

# example: WINDOW, COLORS, etc. are tables, and should be represented as [window], [colors], respectively.
# This is simple. If not clear, do several trials and errors.

# Below is my initial set-up. The TOML homepage (https://toml.io/en/v1.0.0) was very helpful in figuring this out. 
# I put the file alacritty.toml in $HOME/.config/alacritty. However it can be kept anywhere among the places mentioned in
# https://github.com/alacritty/alacritty/tree/master#configuration

#import = [
#    "~/.config/alacritty/themes/themes/ayu_dark.toml"
#    ]

[window]

opacity = 0.8

padding.x = 10
padding.y = 10

decorations = "Full"
#decorations_theme_variant = "Dark"

dynamic_title = true

[font]

normal.family = "FantasqueSansM Nerd Font Mono"
bold.family = "FantasqueSansM Nerd Font Mono"
italic.family = "FantasqueSansM Nerd Font Mono"
bold_italic.family = "FantasqueSansM Nerd Font Mono"

size = 8.0

# Colors (Adapted from 'Moonbow')

# Default colors
[colors.primary]
background = '#040F13'
foreground = '#F9D1A8'

# Normal colors
[colors.normal]
black   = '#0A0E14'
red     = '#DA1D1D'
green   = '#3DBF77'
yellow  = '#DA8E1D'
blue    = '#2660B5'
magenta = '#9F3F71'
cyan    = '#64DCDC'
white   = '#F2E5BC'

# Bright colors
[colors.bright]
black   = '#0A0E14'
red     = '#DA1D1D'
green   = '#3DBF77'
yellow  = '#DA8E1D'
blue    = '#2660B5'
magenta = '#9F3F71'
cyan    = '#64DCDC'
white   = '#FFFFFF'
